add hw
Kseniia30/nodejs-homework pull request #1
Opened 2022-12-26 14:46 UTC by Kseniia30

2022-12-26 16:19 UTC, KhYulian commented on models/contacts.js
> +});
виносьте схеми Joi в окремі файли utils/validation/validationSchemaName.js (const schema = Joi.object(...))

2022-12-26 16:20 UTC, KhYulian commented on models/contacts.js
> +const listContacts = async () => {
перейменуйте в getContacts

2022-12-26 16:21 UTC, KhYulian commented on models/contacts.js
> +  const { name, email, phone } = await schema.validateAsync(body);
також потрібно обробляти можливі помилки при валідації

2022-12-26 16:23 UTC, KhYulian commented on routes/api/contacts.js
> +  const contacts = await listContacts();
const contacts = await listContacts(); - обовязково потрібно розміщувати в блоці try

2022-12-26 16:25 UTC, KhYulian requested changes
Потрібне доопрацювання

2022-12-28 18:02 UTC, KhYulian commented on routes/api/contacts.js
> +    res.json(contacts);
res.status(200).json(contacts) аналогічно в інших місцях

2022-12-28 18:04 UTC, KhYulian reviewed
Потрібні правки

2022-12-28 18:08 UTC, Kseniia30 commented on models/contacts.js
> +});
додано utils/validation/validationSchemaAdding.js
              utils/validation/validationSchemaUpdatng.js

2022-12-28 18:09 UTC, Kseniia30 commented on models/contacts.js
> +const listContacts = async () => {
переіменовано в getContacts

2022-12-28 18:09 UTC, Kseniia30 commented on models/contacts.js
> +  const { name, email, phone } = await schema.validateAsync(body);
в validationSchemaAdding.js та в validationSchemaUpdatng.js перероблено через try/catch

2022-12-28 18:10 UTC, Kseniia30 commented on routes/api/contacts.js
> +  const contacts = await listContacts();
всі основні дії перенесено в try{}

2022-12-28 18:19 UTC, Kseniia30 commented on routes/api/contacts.js
> +    res.json(contacts);
get all, delete, post, put виводять результатом весь список контактів
get by id виводить лиiе контакт з відповідним id

2022-12-28 18:29 UTC, Kseniia30 commented on routes/api/contacts.js
> +    res.json(contacts);
added chains

2022-12-28 18:36 UTC, KhYulian approved these changes
Great job! :heart:

2022-12-28 18:36 UTC, merged