add
Kseniia30/nodejs-homework pull request #3
Opened 2023-01-22 12:55 UTC by Kseniia30

2023-01-22 16:56 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-22 16:56 UTC, KhYulian commented on middlewares/validation/loginValidation.js
> +});
виенсіть const schema в окремий файл

2023-01-22 16:56 UTC, KhYulian commented on middlewares/validation/registrationValidation.js
> +});
теж винесіть

2023-01-22 16:56 UTC, KhYulian commented on models/contacts.js
> +  await Contacts.findOneAndRemove({ _id: contactId, owner });
А якщо контакт не знайдено? Потрібно обробити цей сценарій

2023-01-22 16:56 UTC, KhYulian commented on models/contacts.js
> +  await Contacts.findOneAndRemove({ _id: contactId, owner });
findOneAndRemove повертає результат. Можете його вивчити

2023-01-22 16:56 UTC, KhYulian commented on models/users.js
> +  return user;
Переконайтесь, що ви не повертаєте поле password у респонсі. Можете перед return user; написати user.password = null; Або вирішити це патання іншим чином

2023-01-22 16:56 UTC, KhYulian commented on models/users.js
> +  const isPasswordCorrect = await bcrypt.compare(password, candidate.password);
Якщо юзера не знайдено candidate буде null і ви отримаєте помилку candidate.password. Використовуйте optional chaining candidate?.password

2023-01-22 18:24 UTC, Kseniia30 commented on middlewares/validation/registrationValidation.js
> +});
done

2023-01-22 18:25 UTC, Kseniia30 commented on middlewares/validation/loginValidation.js
> +});
done

2023-01-22 18:25 UTC, Kseniia30 commented on models/contacts.js
> +  await Contacts.findOneAndRemove({ _id: contactId, owner });
done

2023-01-22 18:25 UTC, Kseniia30 commented on models/users.js
> +  return user;
done

2023-01-22 18:26 UTC, Kseniia30 commented on models/users.js
> +  const isPasswordCorrect = await bcrypt.compare(password, candidate.password);
done

2023-01-23 07:36 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-23 07:36 UTC, merged